version: 0.0
os: linux

# TODO 각자 경로에 맞게 수정해줘야 함
files:
  - source:  /
    destination: /home/ec2-user/spring-docker-aws-deploy-java17-live
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
